### PR TITLE
perf(QueryBuilder): responsive layout

### PR DESCRIPTION
**Pull request by MEsteves22**
Small refactor of the query builder component to make it responsive. 

Since we don't have any DS specs for this component, let me know if you think the changes regarding responsiveness should be different.

### CODE REVIEW

**Comment by MEsteves22** [comment]
The changes on Applitools are expected.

**Review by zettca — COMMENTED** [review]
Looking good 👍 

Can we get rid of the `HvGrid`s on the add buttons? It's overlapping the "links" and we're not even using the breakpoints

image

Maybe we could do the same for the the AND/OR combinators and the Delete query buttons - they're not leveraging the breakpoints either

**Comment by MEsteves22** [comment]
@zettca Updated: I removed the unnecessary grids from the rule group component. I had to adjust the spacing since removing the grids increased it (the grids were adding a negative margin). 

I also updated the numeric value CSS because I noticed the inputs were not responsive on lower screen widths.

**Review by zettca — APPROVED** [review]
LGTM 👍

**Pull request merged**
